BWAN-5290:: Upgrade openssl to3.0.13
infiotinc/bwanclient-3p pull request #11
Opened 2024-05-24 11:00 UTC by sanandchoubey

2024-05-24 11:01 UTC, sunilfff approved these changes

2024-05-24 11:41 UTC, sunilfff requested changes
@sanandchoubey pls make changes to ensure the old client's 104.x can use v3.0.7 and only 105 can use v3.0.10

2024-05-24 13:16 UTC, sanandchoubey commented
> @sanandchoubey pls make changes to ensure the old client's 104.x can use v3.0.7 and only 105 can use v3.0.10

@sunilfff this change is for 104 only.  I recommend, rel-bwan-103 branch should be created and 103 should be built using that. And future branch should be built with latest.

2024-05-28 16:01 UTC, sunilfff approved these changes

2024-05-29 05:35 UTC, merged